/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuoteTypeRouteImport } from './routes/quote.$type'
import { Route as ApiCheckQuoteDecisionsRouteImport } from './routes/api.check-quote-decisions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteTypeRoute = QuoteTypeRouteImport.update({
  id: '/quote/$type',
  path: '/quote/$type',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckQuoteDecisionsRoute = ApiCheckQuoteDecisionsRouteImport.update({
  id: '/api/check-quote-decisions',
  path: '/api/check-quote-decisions',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/check-quote-decisions': typeof ApiCheckQuoteDecisionsRoute
  '/quote/$type': typeof QuoteTypeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/check-quote-decisions': typeof ApiCheckQuoteDecisionsRoute
  '/quote/$type': typeof QuoteTypeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/check-quote-decisions': typeof ApiCheckQuoteDecisionsRoute
  '/quote/$type': typeof QuoteTypeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/check-quote-decisions' | '/quote/$type'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/check-quote-decisions' | '/quote/$type'
  id: '__root__' | '/' | '/api/check-quote-decisions' | '/quote/$type'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiCheckQuoteDecisionsRoute: typeof ApiCheckQuoteDecisionsRoute
  QuoteTypeRoute: typeof QuoteTypeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote/$type': {
      id: '/quote/$type'
      path: '/quote/$type'
      fullPath: '/quote/$type'
      preLoaderRoute: typeof QuoteTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/check-quote-decisions': {
      id: '/api/check-quote-decisions'
      path: '/api/check-quote-decisions'
      fullPath: '/api/check-quote-decisions'
      preLoaderRoute: typeof ApiCheckQuoteDecisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiCheckQuoteDecisionsRoute: ApiCheckQuoteDecisionsRoute,
  QuoteTypeRoute: QuoteTypeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
